# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cd9d7573e658092696149a6f506dc2be7739d95c4f82e2c0a9633237f851dd900d7a8e5cdf262214fa7aef29e44107ffdb79df38493085414cd8939336d4ac7

test:
  secret_key_base: 1f82dc1cbbdf5f96a2de3cd85f3457d62cac8583aa4a201c613837ec7233de336abcb8559045676d2c599b82dea6d7ff96e94bc90c64dffe20aa948156f18cae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
